//--------------------------------------------------
// Enumerations of System Timer Events
//--------------------------------------------------
    _SYSTEM_TIMER_EVENT_SOURCE_CLEAR_DETECTING,
    _SYSTEM_TIMER_EVENT_JUDGE_ACTIVE_STATE,
    _SYSTEM_TIMER_EVENT_JUDGE_NOSUPPORT_STATE,
    _SYSTEM_TIMER_EVENT_JUDGE_NOSIGNAL_STATE,
    _SYSTEM_TIMER_EVENT_POWER_FAKE_OFF_TO_OFF,

#if(_HP_SOURCE_SCAN_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_SOURCE_HP_CANCEL_MANUAL_SWITCH_PORT,
#endif
#if(_SOURCE_AUTO_SEARCH_STYLE == _SOURCE_POLLING_ASUS_STYLE)
    _SYSTEM_TIMER_EVENT_SOURCE_ASUS_START_AUTO,
#endif
#if(_SOURCE_AUTO_SEARCH_STYLE == _SOURCE_POLLING_EIZO_STYLE)
    _SYSTEM_TIMER_EVENT_SOURCE_EIZO_SEARCH_FINISH,
#endif
#if(((_D6_INPUT_PORT_TYPE != _D6_NO_PORT) && (_D6_INPUT_PORT_SWITCH_FROM == _SWITCH_FROM_D0)) || (_DP_EMBEDDED_SWITCH_SUPPORT_TYPE == _DP_EMBEDDED_SWITCH_2_DP))
    _SYSTEM_TIMER_EVENT_SOURCE_DP_SWITCH_TIMEOUT,
#endif

#if(_EMBEDDED_DAC_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_AUDIO_DAC_WAIT_VCM_INITIAL,
    _SYSTEM_TIMER_EVENT_AUDIO_DAC_WAIT_VCM_CHARGE,
    _SYSTEM_TIMER_EVENT_AUDIO_DAC_WAIT_DEPOP_TO_NORMAL,
#endif // End of #if(_EMBEDDED_DAC_SUPPORT == _ON)

#if(_D0_DP_TYPE_C_PORT_CTRL_SUPPORT == _ON)

#if(_D0_DP_TYPE_C_DISCRETE_PORT_CTRL_LINK == _DISCRETE_PORT_CTRL_USE_SMBUS)
    _SYSTEM_TIMER_EVENT_D0_TYPE_C_CABLE_DETECT,
#else
    _SYSTEM_TIMER_EVENT_D0_TYPE_C_UNATTACH,
#endif

#if(_D0_DP_TYPE_C_HUB_COMMUNICATION_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_D0_USBHUB_DETECT,
#endif

#if(_D0_BILLBOARD_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_D0_ENABLE_BILLBOARD,
#endif
#endif

#if(_D1_DP_TYPE_C_PORT_CTRL_SUPPORT == _ON)

#if(_D1_DP_TYPE_C_DISCRETE_PORT_CTRL_LINK == _DISCRETE_PORT_CTRL_USE_SMBUS)
    _SYSTEM_TIMER_EVENT_D1_TYPE_C_CABLE_DETECT,
#else
    _SYSTEM_TIMER_EVENT_D1_TYPE_C_UNATTACH,
#endif

#if(_D1_DP_TYPE_C_HUB_COMMUNICATION_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_D1_USBHUB_DETECT,
#endif

#if(_D1_BILLBOARD_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_D1_ENABLE_BILLBOARD,
#endif
#endif

#if(_D2_DP_TYPE_C_PORT_CTRL_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_D2_TYPE_C_CABLE_DETECT,
#if(_D2_DP_TYPE_C_HUB_COMMUNICATION_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_D2_USBHUB_DETECT,
#endif
#endif

#if(_D6_DP_TYPE_C_PORT_CTRL_SUPPORT == _ON)

#if(_D6_DP_TYPE_C_DISCRETE_PORT_CTRL_LINK == _DISCRETE_PORT_CTRL_USE_SMBUS)
    _SYSTEM_TIMER_EVENT_D6_TYPE_C_CABLE_DETECT,
#else
    _SYSTEM_TIMER_EVENT_D6_TYPE_C_UNATTACH,
#endif

#if(_D6_DP_TYPE_C_HUB_COMMUNICATION_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_D6_USBHUB_DETECT,
#endif

#if(_D6_BILLBOARD_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_D6_ENABLE_BILLBOARD,
#endif
#endif

#if(_AIO_MODERN_STANDBY_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_AIO_MODERN_STANDBY_MODE_TIMEOUT,
#endif

#if(_AUTO_TEST_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_AUTO_TEST_OSD_SWITCH_CTRL,
#endif